name: ${project.name}
version: ${project.version}
main: ${mainClass}
author: upperlevel
description: ${project.description}
softdepend: [PlaceholderAPI]

commands:
  uppercore:
    description: 'Commands for Uppercore.'